# Max Violation = How many times the player can being detected before being banned. The rest is understandable.
Bans:
  enabled: false
  message-enabled: true
  max-vl: 30
  message: "&8[&dVenom&8] &d// &f%player% &7has been removed for using &dUnfair Advantages."
  command: "ban %player% Unfair Advantages."
# Message = Displays information about the cheat the player is using. Debug = ignore.
Alerts:
  message: "&8[&dVenom&8] &d// &f%player% &7has flagged &f%check% %type% &d(x%vl%)"
  debug: true
#Change the permission of the alerts.
Permissions:
  alert: "venom.alert"